// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPqxzsgQjW3nrTCvOW4tsL0RS6ms3_W-8',
    appId: '1:975527246570:web:341f97b20ea068be32f593',
    messagingSenderId: '975527246570',
    projectId: 'smart-stitch-8e4ad',
    authDomain: 'smart-stitch-8e4ad.firebaseapp.com',
    storageBucket: 'smart-stitch-8e4ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXNhd2T77BQZfXYudh1_a-Uti3Fjzrz0c',
    appId: '1:975527246570:android:14f96d4f98d5a92432f593',
    messagingSenderId: '975527246570',
    projectId: 'smart-stitch-8e4ad',
    storageBucket: 'smart-stitch-8e4ad.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPqxzsgQjW3nrTCvOW4tsL0RS6ms3_W-8',
    appId: '1:975527246570:web:f093198f12acdf0d32f593',
    messagingSenderId: '975527246570',
    projectId: 'smart-stitch-8e4ad',
    authDomain: 'smart-stitch-8e4ad.firebaseapp.com',
    storageBucket: 'smart-stitch-8e4ad.firebasestorage.app',
  );

}